codecov:
    bot: "codecov-io"
    require_ci_to_pass: no

coverage:
  status:
    project:
      default:
        # Project must always have at least 80% coverage (by line)
        target: 80%
        # Whole-project test coverage is allowed to drop up to 5%. (For situations where we delete code with full coverage)
        threshold: 5%
    patch:
      default:
        # Changes must have at least 80% test coverage (by line)
        target: 80%
